### ISSUE TITLE
Volumes sync

### ISSUE THREAD

**Issue by pyvandenbussche** [ipedrazas/taiga-docker#23]
Hi, another question, what would be the directory we need to sync between the containers and the host so we have all data saved even though a container would crash, etc.
Cheers!

**Comment by ipedrazas** [comment]
It's the one postgres stores the data. Instead of doing this:

`docker run -d --name postgres  postgres`

you have to mount a volume:

`docker run -d -v /data/taiga:/var/lib/postgresql/data/pgdata  --name postgres  postgres`

[Read this](https://hub.docker.com/_/postgres/)  to understand better how it works. I'm using the official postgres image.

My advise is to use an EBS (ssd) and mount it as `/data/taiga`

**Comment by pyvandenbussche** [comment]
Cheers!
